### ISSUE TITLE
home_page_id

### ISSUE THREAD

**Issue by retlehs** [roots/wp-cli-theme-activation#1]
this command came from https://gist.github.com/retlehs/355a709167c25451a691

`home_id` in the bash script works, but `$home_page_id` in this command does not

**Comment by QWp6t** [comment]
`\WP_CLI::run_command()` always returns `null`. You'll have to use `wp_insert_post()`, which will return the ID of the post, as you're expecting.

``` php
    if ($home_page_id = wp_insert_post($home_page_options, false)) {
      \WP_CLI::run_command(['option', 'update', 'show_on_front', $options['show_on_front']]);
      \WP_CLI::run_command(['option', 'update', 'page_on_front', $home_page_id]);
    }
```
